name: CI Pipeline
on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    name: npm test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build docker image
      run: docker build -t test .

    - name: Run container
      run: docker run -p 9000:8080 test

    - name: runtime interface emulator
      run: curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{}'
