name: "CI Pipeline"
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

env:
  SERVICE: resize
  TF_VERSION: 0.14.0

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build docker image
      run: docker build -t ${{ env.SERVICE }} .

    - name: Run container
      run: docker run -dt -p 9000:8080 ${{ env.SERVICE }}

    - name: Runtime emulator
      run: curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{}'
